### PR TITLE
Add env.bat and env.ps1 files for Windows support

### PR DESCRIPTION
**Pull request by Aos-dev**

### CODE REVIEW

**Review by RockHoward — COMMENTED** [review]
It would be much cooler if we could detect 'cmd' mode or 'powershell' mode and then only emit the one required file instead of three. Is that doable?

**Comment by Aos-dev** [comment]
Actually, this is how I started it in the beginning but then came this change: https://github.com/RadGuild/revup/commit/39a4f77ea5333265efaa884b3b1b7404947bfa6b and the variables are no longer taken from the environment but read from the file. So if I were to create just one file, then the part of resolving the variables in json would have to be written three times depending on which file was created.
Alternatively we can rethink the approach to resolving the variables in json so that it does not depend on this file. This sounds the most reasonable to me. I would welcome a suggestion how to adjust and I can code it this way.

**Comment by RockHoward** [comment]
Sorry I have been distracted. Here is my suggestion to resolve this issue. If we detect that we are on Windows then emit all three files but if we are not on windows then only emit .env.

**Comment by Aos-dev** [comment]
Changed as requested, please check.

**Review by RockHoward — APPROVED** [review]

**Pull request merged**
